language: node_js
node_js:
    - 0.10
before_deploy: "grunt build"
deploy:
    provider: s3
    access_key_id: "AKIAIA7MD7RZGECUCCHQ"
    secret_access_key: "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"
    bucket: "skinnybrit51.com"
    upload_dir: "booty-grid"
    skip_cleanup: true
    local-dir: public
    on:
        branch: master
        repo: booty-grid
